RD-4653-support-tf-vars
cloudify-cosmo/cloudify-terraform-plugin pull request #164
Opened 2022-04-14 12:23 UTC by Nelynehemia

2022-04-20 14:34 UTC, EarthmanT requested changes

2022-04-20 14:34 UTC, EarthmanT commented on cloudify_tf/decorators.py
> +            tf = Terraform.from_ctx(terraform_source=terraform_source,
but we need CTX here!

2022-04-21 06:18 UTC, Nelynehemia commented on cloudify_tf/decorators.py
> +            tf = Terraform.from_ctx(terraform_source=terraform_source,
True I know, there is ctx inside the kwargs so there was an error that the function gets double ctx so I deleted it.

2022-04-21 12:56 UTC, EarthmanT submitted a review, later dismissed

2022-04-21 12:56 UTC, EarthmanT commented on cloudify_tf/decorators.py
> +            tf = Terraform.from_ctx(terraform_source=terraform_source,
Oh yeah!

2022-04-21 13:24 UTC, EarthmanT submitted a review, later dismissed

2022-04-24 13:11 UTC, EarthmanT approved these changes

2022-04-24 13:13 UTC, merged